import {useEffect,useState} from 'react'
import AdminLayout from '../admin/layouts/AdminLayout'
import Icon from '../components/common/Icon'
import {apiGet,apiPatch} from '../lib/api'

export default function AdminReportsPage(){
 const[data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState('')
 async function load(){setLoading(true);setError('');try{const q=filter==='all'?'':'?status='+encodeURIComponent(filter);const x=await apiGet('/api/admin/reports'+q);setData(x.reports||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[filter])
 async function setStatus(id,status){setBusy(id);setError('');try{await apiPatch('/api/admin/reports/'+id,{status});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 return <AdminLayout><div className="space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.2em] text-[#ff4655]">ADMIN / SAFETY</p><h1 className="mt-1 text-2xl font-display font-black uppercase text-white">Moderation reports</h1><p className="mt-1 text-xs text-neutral-500">Review community reports without leaving the console.</p></div><div className="flex items-center gap-2"><Icon name="filter" size={14} className="text-neutral-500"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-white/10 bg-[#111116] px-3 py-2 text-xs text-neutral-300"><option value="all">All reports</option><option value="open">Open</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></div></div>
  {error&&<div className="rounded-xl border border-[#ff4655]/20 bg-[#ff4655]/5 p-3 text-xs text-[#ff6674]">{error}</div>}
  {loading?<div className="rounded-2xl border border-white/10 p-10 text-center text-sm text-neutral-500">Loading reports…</div>:!data.length?<div className="rounded-2xl border border-dashed border-white/10 p-12 text-center"><Icon name="check" size={24} className="mx-auto text-emerald-400"/><p className="mt-3 text-sm font-bold text-white">No reports in this view</p><p className="mt-1 text-xs text-neutral-600">The moderation queue is clear.</p></div>:<div className="space-y-3">{data.map(r=><article key={r.id} className="rounded-2xl border border-white/10 bg-white/[.02] p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-wider text-[#ff4655]">{r.target_type}</span><h2 className="mt-1 font-bold text-white">{r.reason}</h2></div><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] uppercase text-neutral-500">{r.status||'open'}</span></div><p className="mt-3 text-sm leading-6 text-neutral-400">{r.details||'No additional details.'}</p><div className="mt-4 flex flex-wrap gap-2">{['reviewing','resolved','dismissed'].map(s=><button key={s} disabled={busy===r.id} onClick={()=>setStatus(r.id,s)} className="rounded-lg border border-white/10 px-3 py-1.5 text-[11px] font-bold uppercase text-neutral-400 hover:border-[#ff4655]/40 hover:text-white disabled:opacity-40">{s}</button>)}</div></article>)}</div>}
 </div></AdminLayout>
}
