import { useEffect, useMemo, useState } from 'react'
import AdminLayout from '../admin/layouts/AdminLayout'
import Icon from '../../components/common/Icon'
import { apiGet, apiPatch, apiPost } from '../../lib/api'

export default function AdminUsersPage(){
 const[data,setData]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[busy,setBusy]=useState('');const[createOpen,setCreateOpen]=useState(false);const[create,setCreate]=useState({email:'',display_name:'',role:'user'});const[creating,setCreating]=useState(false)
 async function load(){setLoading(true);setError('');try{const b=await apiGet('/api/admin/users?per_page=100');setData(b.users||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>data.filter(u=>{const p=u.profile||{};const q=search.toLowerCase().trim();return !q||[u.email,p.email,p.display_name,u.id].some(v=>String(v||'').toLowerCase().includes(q))}),[data,search])
 async function role(id,role){setBusy(id);setError('');try{await apiPatch('/api/admin/users/'+id+'/role',{role});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 async function ban(id,banned){if(!window.confirm(banned?'Ban this account?':'Unban this account?'))return;setBusy(id);setError('');try{await apiPatch('/api/admin/users/'+id+'/ban',{banned});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 return <AdminLayout><div className="space-y-5">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.2em] text-[#ff4655]">ADMIN / ACCESS</p><h1 className="mt-1 text-2xl font-display font-black uppercase text-white">User management</h1><p className="mt-1 text-xs text-neutral-500">{data.length} accounts loaded · roles, moderation and account status</p></div><button onClick={()=>setCreateOpen(true)} className="rounded-xl bg-[#ff4655] px-4 py-2.5 text-[10px] font-black uppercase tracking-wider text-white">+ Create user</button><div className="relative w-full sm:w-80"><Icon name="search" size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email or ID" className="w-full rounded-xl border border-white/10 bg-white/[.03] py-2.5 pl-9 pr-3 text-sm text-white outline-none placeholder:text-neutral-600"/></div></div>
  {error&&<div className="rounded-xl border border-[#ff4655]/20 bg-[#ff4655]/5 p-3 text-xs text-[#ff6674]">{error}</div>}
  <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.015]"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-white/[.03]"><tr><th className="p-3 text-left text-[10px] uppercase tracking-wider text-neutral-500">User</th><th className="p-3 text-left text-[10px] uppercase tracking-wider text-neutral-500">Role</th><th className="p-3 text-left text-[10px] uppercase tracking-wider text-neutral-500">Joined</th><th className="p-3 text-left text-[10px] uppercase tracking-wider text-neutral-500">Last sign in</th><th className="p-3 text-left text-[10px] uppercase tracking-wider text-neutral-500">Status</th><th className="p-3 text-right text-[10px] uppercase tracking-wider text-neutral-500">Actions</th></tr></thead><tbody>
  {filtered.map(u=>{const p=u.profile||{};const name=p.display_name||u.user_metadata?.full_name||u.email?.split('@')[0]||'User';const banned=!!u.banned_until&&new Date(u.banned_until)>new Date();return <tr key={u.id} className="border-t border-white/[.06]"><td className="p-3"><div className="flex items-center gap-3">{p.avatar_url?<img src={p.avatar_url} alt="" className="h-9 w-9 rounded-full object-cover"/>:<div className="flex h-9 w-9 items-center justify-center rounded-full bg-white/[.06] text-[10px] font-bold text-neutral-400">{name.slice(0,2).toUpperCase()}</div>}<div className="min-w-0"><div className="font-bold text-white">{name}</div><div className="max-w-[260px] truncate text-[11px] text-neutral-600">{u.email}</div></div></div></td><td className="p-3"><select value={p.role||'user'} disabled={busy===u.id} onChange={e=>role(u.id,e.target.value)} className="rounded-lg border border-white/10 bg-[#121218] px-2 py-1.5 text-xs text-neutral-300"><option value="user">User</option><option value="moderator">Moderator</option><option value="admin">Admin</option></select></td><td className="p-3 text-xs text-neutral-500">{u.created_at?new Date(u.created_at).toLocaleDateString():'—'}</td><td className="p-3 text-xs text-neutral-500">{u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():'Never'}</td><td className="p-3"><span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-[10px] font-bold ${banned?'bg-[#ff4655]/10 text-[#ff6674]':'bg-emerald-500/10 text-emerald-400'}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{banned?'Banned':'Active'}</span></td><td className="p-3 text-right"><button onClick={()=>ban(u.id,!banned)} disabled={busy===u.id} title={banned?'Unban user':'Ban user'} aria-label={banned?'Unban user':'Ban user'} className="rounded-lg border border-white/10 p-2 text-neutral-500 hover:text-white disabled:opacity-40"><Icon name={banned?'check':'ban'} size={15}/></button></td></tr>})}
  </tbody></table></div>{loading&&<div className="p-8 text-center text-sm text-neutral-500">Loading users…</div>}{!loading&&!filtered.length&&<div className="p-10 text-center text-sm text-neutral-600">No users match this search.</div>}</div>
 </div>{createOpen&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={async e=>{e.preventDefault();setCreating(true);setError('');try{await apiPost('/api/admin/users',create);setCreate({email:'',display_name:'',role:'user'});setCreateOpen(false);await load()}catch(err){setError(err.message)}finally{setCreating(false)}}} className="w-full max-w-md space-y-4 rounded-2xl border border-white/10 bg-[#0c0c11] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-mono uppercase tracking-wider text-[#ff4655]">ADMIN / ACCOUNT</p><h2 className="mt-1 text-lg font-black text-white">Create user</h2></div><button type="button" onClick={()=>setCreateOpen(false)} className="text-neutral-500 hover:text-white">×</button></div><input required type="email" placeholder="Email address" value={create.email} onChange={e=>setCreate({...create,email:e.target.value})} className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-3 text-sm text-white outline-none"/><input placeholder="Display name" value={create.display_name} onChange={e=>setCreate({...create,display_name:e.target.value})} className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-3 text-sm text-white outline-none"/><select value={create.role} onChange={e=>setCreate({...create,role:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#121218] px-3 py-3 text-sm text-white"><option value="user">User</option><option value="moderator">Moderator</option><option value="admin">Admin</option></select><p className="text-[11px] leading-5 text-neutral-600">An invitation is generated for the email. The account is created without exposing a password to the administrator.</p><button disabled={creating} className="w-full rounded-xl bg-[#ff4655] py-3 text-xs font-black uppercase tracking-wider text-white disabled:opacity-40">{creating?'Creating…':'Create & invite'}</button></form></div>}</AdminLayout>
}
