import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import MainLayout from '../layouts/MainLayout'
import Icon from '../components/common/Icon'
import PostMedia from '../components/common/PostMedia'

export default function BookmarksPage(){
 const{user}=useAuth();const[data,setData]=useState([]);const[profiles,setProfiles]=useState({});const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 async function load(){if(!user){setLoading(false);return}setLoading(true);const{data:rows,error:e}=await supabase.from('post_bookmarks').select('post_id,created_at,posts(id,author_id,content,media_url,media_type,created_at,status)').eq('user_id',user.id).order('created_at',{ascending:false});if(e){setError(e.message);setLoading(false);return}const posts=(rows||[]).map(x=>x.posts).filter(Boolean).filter(x=>x.status==='published');setData(posts);const ids=[...new Set(posts.map(p=>p.author_id))];if(ids.length){const{data:ps}=await supabase.rpc('get_public_profiles',{p_ids:ids});setProfiles(Object.fromEntries((ps||[]).map(p=>[p.id,p])))}setLoading(false)}
 useEffect(()=>{load()},[user?.id])
 if(!user)return <MainLayout><div className="mx-auto max-w-xl py-20 text-center"><Icon name="bookmark" size={28} className="mx-auto text-[#ff4655]"/><h1 className="mt-4 font-display text-2xl font-black uppercase text-white">Sign in to see saved posts</h1></div></MainLayout>
 return <MainLayout><div className="mx-auto max-w-3xl"><div><p className="font-mono text-[10px] tracking-[.25em] text-[#00e5ff]">YOUR LIBRARY</p><h1 className="mt-1 font-display text-3xl font-black uppercase text-white">Saved posts</h1></div>{error&&<div className="mt-4 rounded-xl border border-[#ff4655]/20 bg-[#ff4655]/5 p-3 text-xs text-[#ff6674]">{error}</div>}<div className="mt-6 space-y-3">{loading&&<p className="text-sm text-neutral-600">Loading saved posts…</p>}{!loading&&!data.length&&<div className="rounded-2xl border border-dashed border-white/10 p-12 text-center"><Icon name="bookmark" size={25} className="mx-auto text-neutral-700"/><p className="mt-3 text-sm text-neutral-600">Save posts you want to come back to.</p></div>}{data.map(p=>{const profile=profiles[p.author_id];return <Link key={p.id} to={'/posts/'+p.id} className="block overflow-hidden rounded-2xl border border-white/[.07] bg-[#0d0d12] transition hover:border-white/15"><div className="p-4"><div className="flex items-center gap-2"><div className="h-7 w-7 overflow-hidden rounded-full">{profile?.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center bg-white/[.06] text-[9px] font-bold text-neutral-400">{(profile?.display_name||'P').slice(0,2).toUpperCase()}</div>}</div><span className="text-xs font-bold text-white">{profile?.display_name||'Player'}</span><span className="text-[10px] text-neutral-600">· {new Date(p.created_at).toLocaleDateString()}</span></div><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm leading-6 text-neutral-300">{p.content}</p></div><PostMedia url={p.media_url} mediaType={p.media_type} compact/></Link>})}</div></div></MainLayout>
}