import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import MainLayout from '../layouts/MainLayout'
import Icon from '../components/common/Icon'

function Avatar({profile}){const n=profile?.display_name||'Player';return profile?.avatar_url?<img src={profile.avatar_url} alt="" className="h-12 w-12 rounded-full object-cover"/>:<div className="flex h-12 w-12 items-center justify-center rounded-full bg-gradient-to-br from-[#ff4655] to-[#00e5ff] text-xs font-black text-white">{n.slice(0,2).toUpperCase()}</div>}

export default function FollowingPage(){
 const{user}=useAuth();const[data,setData]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 async function load(){if(!user){setLoading(false);return}setLoading(true);const{data:rows,error:e}=await supabase.from('user_follows').select('following_id,created_at').eq('follower_id',user.id).order('created_at',{ascending:false});if(e){setError(e.message);setLoading(false);return}const ids=(rows||[]).map(x=>x.following_id);if(!ids.length){setData([]);setLoading(false);return}const{data:profiles,error:pe}=await supabase.rpc('get_public_profiles',{p_ids:ids});if(pe){setError(pe.message);setLoading(false);return}const map=Object.fromEntries((profiles||[]).map(p=>[p.id,p]));setData((rows||[]).map(x=>({...x,profile:map[x.following_id]})));setLoading(false)}
 useEffect(()=>{load()},[user?.id])
 async function unfollow(id){const{error:e}=await supabase.from('user_follows').delete().eq('follower_id',user.id).eq('following_id',id);if(e)setError(e.message);else load()}
 if(!user)return <MainLayout><div className="mx-auto max-w-xl py-20 text-center"><Icon name="users" size={28} className="mx-auto text-[#ff4655]"/><h1 className="mt-4 font-display text-2xl font-black uppercase text-white">Sign in to see Following</h1></div></MainLayout>
 return <MainLayout><div className="mx-auto max-w-3xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] tracking-[.25em] text-[#00e5ff]">SOCIAL GRAPH</p><h1 className="mt-1 font-display text-3xl font-black uppercase text-white">Following</h1><p className="mt-2 text-sm text-neutral-500">People and creators you follow. This is separate from streamer subscriptions.</p></div><Link to="/subscriptions" className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-[10px] font-black uppercase text-neutral-300 hover:text-white"><Icon name="eye" size={15}/>Streamer subscriptions</Link></div>{error&&<div className="mt-4 rounded-xl border border-[#ff4655]/20 bg-[#ff4655]/5 p-3 text-xs text-[#ff6674]">{error}</div>}<div className="mt-6 space-y-2">{loading&&<p className="text-sm text-neutral-600">Loading people…</p>}{!loading&&!data.length&&<div className="rounded-2xl border border-dashed border-white/10 p-12 text-center"><Icon name="users" size={25} className="mx-auto text-neutral-700"/><p className="mt-3 text-sm text-neutral-600">You aren't following anyone yet.</p><Link to="/posts" className="mt-4 inline-flex text-xs font-bold text-[#ff4655]">Discover people</Link></div>}{data.map(x=>{const name=x.profile?.display_name||'Player';return <div key={x.following_id} className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-[#0d0d12] p-4"><Link to={`/profile/${x.following_id}`}><Avatar profile={x.profile}/></Link><Link to={`/profile/${x.following_id}`} className="min-w-0 flex-1"><div className="font-bold text-white">{name}</div><div className="truncate text-xs text-neutral-600">{x.profile?.bio||'VALO community member'}</div></Link><button onClick={()=>unfollow(x.following_id)} title={`Unfollow ${name}`} aria-label={`Unfollow ${name}`} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-[10px] font-black uppercase text-neutral-400 hover:border-[#ff4655]/30 hover:text-[#ff4655]"><Icon name="check" size={13}/>Following</button></div>})}</div></div></MainLayout>
}