import MainLayout from '../layouts/MainLayout'

export default function PrivacyPolicyPage(){
  return <MainLayout><div className="max-w-4xl mx-auto px-4 py-10 text-neutral-400 font-body leading-7 space-y-8">
    <header className="border-b border-white/10 pb-6"><h1 className="text-3xl font-display font-black text-white uppercase tracking-wider">Privacy Policy</h1><p className="text-xs font-mono text-neutral-500 mt-2">LAST UPDATED: October 7, 2026</p><p className="mt-3 text-sm leading-6 text-neutral-500">This policy explains how VALO Community collects, uses, stores and protects personal information when you use the service.</p></header>
    <Section t="1. Who this applies to">This policy applies to VALO Community visitors and registered users who use our website, community features, streamer subscriptions, notifications and related services.</Section>
    <Section t="2. What we collect">When you sign in, we receive account information provided by Supabase Auth, such as your email address and authentication identifiers. We store community profile information you choose to provide, subscriptions, device notification registrations, posts, comments, likes, bookmarks, follows and reports. We collect only information reasonably needed to operate, secure and improve the service.</Section>
    <Section t="3. Public streaming data">We process publicly available streamer information from supported platforms, including channel identity, live status, stream title, thumbnail, viewer count and broadcast URL. This information is used to operate the live directory, history and discovery features and is not treated as private user data.</Section>
    <Section t="4. How we use data">We use information to authenticate users, operate community features, deliver notifications, moderate content, maintain streamer data, provide analytics, respond to support or grievance requests, prevent abuse and keep the service secure.</Section>
    <Section t="5. Legal and regulatory basis">Where applicable, processing is carried out in accordance with applicable Indian data-protection and information-technology laws and rules, including the Digital Personal Data Protection Act, 2023 and rules or notifications made under applicable law. Where another jurisdiction's law applies to a user or processing activity, we will follow the requirements applicable to that activity.</Section>
    <Section t="6. Service providers">The application uses Supabase for database and authentication infrastructure, Vercel for frontend hosting and Render for backend hosting. External streaming platforms provide streamer data. Providers may process data according to their own policies and our instructions where applicable.</Section>
    <Section t="7. Storage and security">Authentication sessions and limited preferences may be stored in browser storage. We use database row-level security and server-side privileged APIs to restrict access to protected data. We apply reasonable technical and organizational safeguards, but no internet service can guarantee absolute security.</Section>
    <Section t="8. Your choices and account deletion">You can update your community profile, manage streamer subscriptions and notification registrations, log out, and permanently delete your account from Settings. Account deletion removes the user-owned application records we control and requests deletion of the Supabase authentication account, subject to records that must be retained for security, moderation, legal or legitimate operational reasons.</Section>
    <Section t="9. Retention">Operational records may be retained where necessary for security, moderation, legal obligations, fraud prevention, dispute handling or service integrity. Public streamer history is not treated as private user data. Retention periods may vary depending on the type and purpose of the record.</Section>
    <Section t="10. Grievances and privacy requests">For privacy requests, complaints, data-protection concerns or other grievances, contact the VALO Community team through the Contact page. Please include enough information for us to identify the relevant account or issue. We will review and respond through the available contact channel, subject to applicable law.</Section>
    <Section t="11. Updates">We may update this policy when the service, law or our data practices change. The latest version and its update date will be published on this page.</Section>
  </div></MainLayout>
}
function Section({t,children}){return <section className="space-y-2"><h2 className="text-white font-display font-black uppercase tracking-wider text-sm">// {t}</h2><p>{children}</p></section>}