import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import MainLayout from '../layouts/MainLayout'
import Icon from '../components/common/Icon'

const reasons=['Spam or misleading','Harassment or bullying','Hate or abusive content','Sexual or explicit content','Violence or threats','Copyright or stolen content','Impersonation','Cheating or harmful activity','Other']

export default function ReportPage(){
 const{user}=useAuth();const nav=useNavigate();const[q]=useSearchParams();const[type,setType]=useState(q.get('type')||'post');const[id,setId]=useState(q.get('id')||'');const[reason,setReason]=useState(reasons[0]);const[details,setDetails]=useState('');const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState('')
 async function submit(e){e.preventDefault();if(!user){setError('Sign in to submit a report.');return}if(!id.trim()){setError('The content to report is missing.');return}setBusy(true);setError('');const{error:e2}=await supabase.from('content_reports').insert({reporter_id:user.id,target_type:type,target_id:id.trim(),reason,details:details.trim()||null});if(e2){setError(e2.code==='23505'?'You already have an open report for this item.':e2.message)}else setDone(true);setBusy(false)}
 if(!user)return <MainLayout><div className="mx-auto max-w-xl py-20 text-center"><Icon name="flag" size={28} className="mx-auto text-[#ff4655]"/><h1 className="mt-4 font-display text-2xl font-black uppercase text-white">Sign in to report</h1></div></MainLayout>
 if(done)return <MainLayout><div className="mx-auto max-w-xl py-20 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-400"><Icon name="check" size={22}/></div><h1 className="mt-4 font-display text-2xl font-black uppercase text-white">Report received</h1><p className="mt-2 text-sm leading-6 text-neutral-500">Thanks. The moderation team will review it.</p><Link to="/posts" className="mt-5 inline-flex rounded-xl bg-[#ff4655] px-4 py-2.5 text-xs font-black uppercase text-white">Back to community</Link></div></MainLayout>
 return <MainLayout><div className="mx-auto max-w-xl"><div className="mb-6"><p className="font-mono text-[10px] tracking-[.25em] text-[#ff4655]">SAFETY / MODERATION</p><h1 className="mt-1 font-display text-3xl font-black uppercase text-white">Report content</h1><p className="mt-2 text-sm text-neutral-500">Tell us what happened. Reports are private and reviewed by the moderation team.</p></div><form onSubmit={submit} className="space-y-4 rounded-[24px] border border-white/[.08] bg-[#0d0d12] p-5 sm:p-6"><label className="block"><span className="mb-2 block text-[10px] font-black uppercase tracking-wider text-neutral-500">What are you reporting?</span><select value={type} onChange={e=>setType(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#121218] p-3 text-sm text-white outline-none"><option value="post">Post</option><option value="comment">Comment</option><option value="user">User</option><option value="streamer">Streamer</option><option value="submission">Streamer submission</option></select></label><label className="block"><span className="mb-2 block text-[10px] font-black uppercase tracking-wider text-neutral-500">Reason</span><select value={reason} onChange={e=>setReason(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#121218] p-3 text-sm text-white outline-none">{reasons.map(x=><option key={x}>{x}</option>)}</select></label><label className="block"><span className="mb-2 block text-[10px] font-black uppercase tracking-wider text-neutral-500">Additional details</span><textarea value={details} onChange={e=>setDetails(e.target.value)} maxLength={2000} rows={5} placeholder="Give the moderators enough context to understand the issue…" className="w-full resize-none rounded-xl border border-white/10 bg-white/[.03] p-3 text-sm text-white outline-none placeholder:text-neutral-600"/></label><div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3 text-[11px] text-neutral-600">Reference: <span className="font-mono text-neutral-400">{id||'Missing target'}</span></div>{error&&<div className="rounded-xl border border-[#ff4655]/20 bg-[#ff4655]/5 p-3 text-xs text-[#ff6674]">{error}</div>}<div className="flex items-center justify-end gap-2"><button type="button" onClick={()=>nav(-1)} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-bold text-neutral-400">Cancel</button><button disabled={busy||!id} className="rounded-xl bg-[#ff4655] px-5 py-2.5 text-xs font-black uppercase text-white disabled:opacity-40">{busy?'Sending…':'Submit report'}</button></div></form></div></MainLayout>
}